const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DECREASE_ITEM: 'DECREASE_ITEM',
  HIDE_CART: 'HIDE_CART',
};

export default CartActionTypes;
